### ISSUE TITLE
Logs from Virtual Schema do not appear in Exasol cluster logs

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/virtual-schema-common-java#124]
## Situation 

If we set   LOG_LEVEL = 'ALL' property while creating virtual schema, the logs do not appear in Exasol cluster logs. As a Virtual Schema user I want to be able to see the logs from Virtual Schema itself in the cluster log files.

**Comment by tkilias** [comment]
UDFs currently can't write in the cluster logs, because they execute untrusted user code which could produce huge amounts of output which might fill up the file system for the logs. Virtual Schemas are implemented as a kind of UDF and, therefore, this also applies for them.

**Comment by redcatbear** [comment]
Currently no fix possible.
