### ISSUE TITLE
Problems with parentheses of generated query

### ISSUE THREAD

**Issue by HadarGreinsmark** [exasol/virtual-schema-common-java#125]
In Exasol version 7.0 there is new IF THEN ELSE syntax, that is rewritten in the query graph to a searched CASE. The rewritten query when doing an EXPLAIN seems to miss some required parentheses necessary to keep the correct precedence.

Example:

```sql
select if 1 < null then 'a' else 'b' endif;
````
should return 'null' and is in the compiler rewritten to the equivalent of

```sql
case when (1 < null) is null then null
     when 1 < null then 'a'
     else 'b'
end
```

When doing an EXPLAIN, it seems like the parentheses are missing and the condition is rewritten wrongly with IS NULL

```sql
-- wrong
1 < null is null  == 1 < true == false
-- expected
(1 < null) is null == null is null == true

```

Is it possible to fix so that parentheses are added during the rewrite?

See internal SPOT-9224 ticket.

**Comment by AnastasiiaSergienko** [comment]
Will be fixed in https://github.com/exasol/virtual-schema-common-jdbc/issues/39
