### ISSUE TITLE
Add capabilities for new HASHTYPE_* functions

### ISSUE THREAD

**Issue by sir-exasol** [exasol/virtual-schema-common-java#126]
In version 7.0.0, we add new hash functions that compute the hash of its arguments and returns the result as a HASHTYPE value instead of CHAR. (See SPOT-7044 for information on the new HASHTYPE type and SPOT-9336 for information on the new HASHTYPE_* functions).
Please add new capabilities for HASHTYPE_MD5, HASHTYPE_SHA1, HASHTYPE_SHA256, HASHTYPE_SHA512, and HASHTYPE_TIGER and make sure that the Exasol dialect pushes them down.

**Comment by AnastasiiaSergienko** [comment]
We need to wait for EXASOL 7.0.alpha2 to test these functions

**Comment by AnastasiiaSergienko** [comment]
Closed with #133
