### ISSUE TITLE
Add capabilities for new scalar function SESSION_PARAMETER 

### ISSUE THREAD

**Issue by milenaossoriolami** [exasol/virtual-schema-common-java#127]
In Exasol version 7.0.0 we add the new scalar function SESSION_PARAMETER for retrieving a session parameter value of a given session. (See SPOT-9377)
Please add a new capability and make sure that the Exasol dialect pushes down the new SESSION_PARAMETER function.

**Comment by AnastasiiaSergienko** [comment]
We need to wait for EXASOL 7.0.alpha2 to test this function.

**Comment by AnastasiiaSergienko** [comment]
Closed with #143
