### ISSUE TITLE
Allow adding adapter specific metadata to SchemaMetadata

### ISSUE THREAD

**Issue by jakobbraun** [exasol/virtual-schema-common-java#137]
Right now it is possible to add adapter specific schema metadata to the `SchemaMetadata`, `TableMetadata` or `ColumnMetadata` using the adapter notes.

If the adapter specific metadata is modeled using classes, one solution is to serialize them into the adapter notes. This is however very inconvenient, as each time the adapter specific metadata is needed, they must be deserialized.

It would be very nice if it would be possible to add adapter specific objects directly to the metadata that get automatically serialized and deserialized. This would however require to make the Metadata classes generic so they can be typed to the adapter specific classes.

**Comment by redcatbear** [comment]
Stale feature. Closing. Can be reopened if it becomes relevant again.
