### ISSUE TITLE
Documentation: Adapter API - document the interface type of the api

### ISSUE THREAD

**Issue by jakobbraun** [exasol/virtual-schema-common-java#156]
https://github.com/exasol/virtual-schemas/blob/master/doc/development/api/virtual_schema_api.md

I miss the information which interface is documenteted here? Is it an http interface? Who are the two parties using this protocol?

**Comment by exanm** [comment]
If we add the sequence diagram, then it should include `getCapabilities` right before `pushdown`.

**Comment by jakobbraun** [comment]
Here an improved suggestion for the diagram:
```
@startuml
"SQL Client" --> "Exasol Core" : Select Request
"Exasol Core" --> "Exasol Core": parse
"Exasol Core" --> "Virtual Schema Adapter": getCapabilities
"Exasol Core" <- "Virtual Schema Adapter": list of capabilities
"Exasol Core" --> "Exasol Core": rewrite to remove unsupported parts
"Exasol Core" --> "Virtual Schema Adapter": pushdown("SELECT ...")
"Exasol Core" <- "Virtual Schema Adapter": "IMPORT FROM JDBC ..."
"Exasol Core" --> Importer: IMPORT FROM JDBC ...
"Exasol Core" <- Importer: rows
"Exasol Core" --> "Exasol Core": post process
"SQL Client" <- "Exasol Core": rows
@enduml
```

![image](https://user-images.githubusercontent.com/18247545/109271797-4b1e0300-7810-11eb-95ef-322ed2a72c25.png)
