### ISSUE TITLE
API Documentation Fixes: selectList

### ISSUE THREAD

**Issue by exanm** [exasol/virtual-schema-common-java#186]
The API documentation for `selectList` is incomplete. Please document the following three options:
* `selectList` is not given: This means `SELECT *`. The field `involvedTables` may be used to get the list of columns.
* `selectList` is an empty array: Select any column/expression. This is used if a query can not be pushed down completely, for example. The adapter may choose something like `SELECT TRUE` to get the correct number of rows.
* Otherwise `selectList` contains the requested select list elements, a list of expressions. The order of the elements matters.

**Comment by jakobbraun** [comment]
@exanm do you refer to `SqlStatementSelect.Builder#selectList`?

**Comment by exanm** [comment]
No, this is about the API documentation. Please review/merge the pull request.

**Comment by exanm** [comment]
Based on the implementation of #188 we should extend the documentation for the first case to:
``` `selectList` is not given: This means `SELECT *`. Adapters requiring an explicit select list can use the field `from` to get the names and aliases of the tables (depth-first search on joins) and the field `involvedTables` to get the columns for each table.```
