### ISSUE TITLE
SELECTLIST_EXPRESSIONS

### ISSUE THREAD

**Issue by jakobbraun** [exasol/virtual-schema-common-java#190]
Please extend the documentation of the capability SELECTLIST_EXPRESSIONS by adding this:
This capability contains a subset of SELECTLIST_PROJECTION. It allows projections, if the select list contains an expression.

Moved from https://github.com/exasol/virtual-schema-common-java/issues/187

**Comment by exanm** [comment]
You changed the documentation for `SELECTLIST_PROJECTION` instead of `SELECTLIST_EXPRESSIONS`.

This ticket was meant as an extension of the following sentence:
> Support expressions in the select list; Additional capabilities are required depending on the expression.
