### ISSUE TITLE
Check why `LOG10` is not mapped

### ISSUE THREAD

**Issue by chiaradiamarcelo** [exasol/virtual-schema-common-java#201]
Currently we map `LN` and `LOG` but not `LOG10`, which is available in Exasol.

**Comment by AnastasiiaSergienko** [comment]
Please, check our API documentation if you have some questions about scalar and aggregate functions. 
https://github.com/exasol/virtual-schema-common-java/blob/main/doc/development/api/scalar_functions_api.md

From the documentation: 
LOG10 -> The API uses the LOG function.

**Comment by chiaradiamarcelo** [comment]
> Please, check our API documentation if you have some questions about scalar and aggregate functions.
> https://github.com/exasol/virtual-schema-common-java/blob/main/doc/development/api/scalar_functions_api.md
> 
> From the documentation:
> LOG10 -> The API uses the LOG function.

Thanks! Closing as this is supported.
