### ISSUE TITLE
Some Numeric Literals Have Wrong Data Type

### ISSUE THREAD

**Issue by exanm** [exasol/virtual-schema-common-java#209]
For some numeric literals the adapter changes the data type from exact to approximate (or vice versa) when generating the pushdown query.

To fix this, please change the format of the numeric literals in the generated pushdown query:
* A **literal_exactnumeric** should always be a number without an "E" in the pushdown query.
Broken example: For `0.000000000000000000000000000000000001` the adapter generates `1E-36`, but should generate `0.000000000000000000000000000000000001`.
* A **literal_double** should always be a number with an "E" in the pushdown query. The format should be `DecimalFormat("0.################E0")`.
Broken example: For `CAST(1 AS DOUBLE)` the adapter generates `1.0`, but should generate `1E0`. Notice, that the CAST does not appear in the pushdown request, instead this is just a literal_double.

Dialects:
* In addition to these changes, the Exasol dialect should always add a `CAST(... AS DOUBLE)` for literal_double. Otherwise some numbers like 1E0 get parsed as DECIMAL.
* Other dialects might require similar adaptions.

**Comment by AnastasiiaSergienko** [comment]
Is it the change I've made for your testing last month?

**Comment by exanm** [comment]
> Is it the change I've made for your testing last month?

Yes, the change for literal_double works, but the change for literal_exactnumeric doesn't work in that prototype.
