### ISSUE TITLE
Examine adapter property EXCEPTION_HANDLING, potentially remove

### ISSUE THREAD

**Issue by ckunki** [exasol/virtual-schema-common-java#269]
Public constants and methods in class `virtual-schema-common-java/AdapterProperties`. 
```java 
String EXCEPTION_HANDLING_PROPERTY = "EXCEPTION_HANDLING";
String getExceptionHandling()
boolean hasExceptionHandling()
```
Currently there is no evidence for usage of this property. If it is unused we can remove the definition.

[Searching in GitHub org `exasol`](https://github.com/search?q=org%3Aexasol+EXCEPTION_HANDLING+NOT+repo%3Aexasol%2Fdb+NOT+repo%3Aexasol%2Fdocs+NOT+repo%3Aexasol%2Fdrivers+NOT+repo%3Aexasol%2Fprj-docs-revamp&type=code) returns usages in
* [https:github.com/exasol/script-languages-internal‎](script-languages-internal‎)
* [https:github.com/exasol/teradata-virtual-schema‎](teradata-virtual-schema‎)
* [https:github.com/exasol/virtual-schema-common-java‎](virtual-schema-common-java‎)
* [https:github.com/exasol/virtual-schema-common-jdbc‎](virtual-schema-common-jdbc‎)

Hits in repositories considered as irrelevant: 
* [https://github.com/exasol/db](db)
* [https://github.com/exasol/docs](docs)
* [https://github.com/exasol/drivers](drivers)
* [https://github.com/exasol/prj-docs-revamp](prj-docs-revamp)

See also 
* https://github.com/exasol/exasol-virtual-schema/issues/85
* #268

**Comment by kaklakariada** [comment]
Marked exception handling property as deprecated in https://github.com/exasol/virtual-schema-common-java/pull/275 as preparation for this.

**Comment by kaklakariada** [comment]
Precondition for implementing this: https://github.com/exasol/virtual-schema-common-jdbc/issues/156
