### ISSUE TITLE
Disable / enable capabilities in `Capabilities.Builder`

### ISSUE THREAD

**Issue by redcatbear** [exasol/virtual-schema-common-java#40]
# Situation
A dialect support a set of capabilities (or five sub-sets of different capability types to be precise). Users can disable individual capabilities through configuration though.

# Acceptance Criteria
1. Capability builder features methods to the builder to disable capabilities (e.g. `disableMain(MainCapability ... capability)`.
1. Capability has methods to query enabled capabilities (e.g. `Set<MainCapability> getEnabledMainCapability()`) which are the supported capabilities minus the disabled ones.
1. By default all capabilities a driver supports are enabled.

**Comment by AnastasiiaSergienko** [comment]
Closed with #41
