### ISSUE TITLE
Rework ColumnMetadata

### ISSUE THREAD

**Issue by redcatbear** [exasol/virtual-schema-common-java#59]
# Situation
While reworking reading of remote metadata I found that the `ColumnMetadata` class has some points that need to be improved.

1. Builder instead of constructor with lots of arguments
1. More robust default value handling
1. More unit test coverage
1. JavaDoc

# Acceptance Criteria
1. Builder
1. `null` and empty string are valid default values
1. Full test coverage
1. JavaDoc added
1. All invocations of the old constructor replaced by builder invocations.

**Comment by AnastasiiaSergienko** [comment]
Closed with #62
