### ISSUE TITLE
Have a unified formatter

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/virtual-schema-common-java#64]
### Problem
Currently there is no consistency in the project formatting.

### Solution
Use Eclipse formatting rules on the project and reformat the code.

**Comment by redcatbear** [comment]
Java formatter rules are checked in already. If I am not mistaken, it's this file:
https://github.com/exasol/virtual-schema-common-java/blob/master/.settings/org.eclipse.jdt.core.prefs
