### ISSUE TITLE
Scalar Function Capability for HASH_SHA256 and HASH_SHA512

### ISSUE THREAD

**Issue by marclorbeer** [exasol/virtual-schema-common-java#65]
New scalar functions for sha256 and sha512 hashing will be introduced in a future Exasol release.
This means that the enum ScalarFunctionCapability (in ScalarFunctionCapability.java) needs to be extended with the following values:

- HASH_SHA256
- HASH_SHA512

**Comment by AnastasiiaSergienko** [comment]
Closed with #78
